version: '3.7'
services:
#  Database-ArangoDB:
#    image: arangodb:3.6.0
#    environment:
#      ARANGO_ROOT_PASSWORD: rootpassword
#    ports:
#      - 8529:8529
#    volumes:
#      - arangodb_data_container:/var/lib/arangodb3
#      - arangodb_apps_data_container:/var/lib/arangodb3-apps

  Application-IAM:
    image: local/iam:latest
    environment:
      ARANGODB_HOSTNAME: 192.168.1.20
    ports:
      - "80:9000"

networks:
  hiveflow:
    ipam:
      driver: default
      config:
        - subnet: 172.99.1.0/16

volumes:
  arangodb_data_container:
  arangodb_apps_data_container: